import hashlib
import importlib
import os
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, cast
from uuid import uuid4

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from fastapi.testclient import TestClient

from backend.app import main
from backend.app.api import v1
from backend.app.api.v1 import jobs


def test_importing_without_a_file_returns_fastapi_validation_error(
    client: TestClient,
) -> None:
    with TestClient(client.app, raise_server_exceptions=False) as error_client:
        response = error_client.post("/api/v1/import")

    assert response.status_code == 422


def test_importing_a_non_gcode_file_is_rejected(client: TestClient) -> None:
    response = client.post(
        "/api/v1/import",
        files={"file": ("print-instructions.pdf", b"%PDF-1.7", "application/pdf")},
    )

    assert response.status_code == 415


def test_importing_a_gcode_file_with_a_generic_browser_media_type_is_accepted(
    client: TestClient,
) -> None:
    content = b"G28\nG1 X10 Y10\n"
    response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                content,
                "application/octet-stream",
            )
        },
    )

    assert response.status_code == 201
    assert response.json()["artifact"] == {
        "id": f"sha256:{hashlib.sha256(content).hexdigest()}",
        "filename": "calibration-cube.gcode",
        "mediaType": "application/octet-stream",
    }


def test_importing_gcode_returns_its_canonical_artifact_and_missing_material_without_queuing_a_job(
    client: TestClient,
) -> None:
    content = b"; generated by test slicer\nG28\nG1 X10 Y10\n"
    response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                content,
                "text/x.gcode",
            )
        },
    )

    assert response.status_code == 201
    assert response.json() == {
        "artifact": {
            "id": f"sha256:{hashlib.sha256(content).hexdigest()}",
            "filename": "calibration-cube.gcode",
            "mediaType": "text/x.gcode",
        },
        "missingPlanningValues": ["material"],
        "diagnostics": [],
    }

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": []}


def test_importing_distinct_gcode_files_with_the_same_filename_returns_distinct_canonical_artifact_references(
    client: TestClient,
) -> None:
    first_import = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; first artifact\nG28\n",
                "text/x.gcode",
            )
        },
    )
    second_import = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; distinct artifact\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    assert first_import.status_code == 201
    assert second_import.status_code == 201
    assert (
        first_import.json()["artifact"]["id"] != second_import.json()["artifact"]["id"]
    )


def test_importing_identical_gcode_content_returns_the_same_canonical_artifact_reference(
    client: TestClient,
) -> None:
    content = b"; generated by test slicer\nG28\nG1 X10 Y10\n"
    first_import = client.post(
        "/api/v1/import",
        files={"file": ("calibration-cube.gcode", content, "text/x.gcode")},
    )
    second_import = client.post(
        "/api/v1/import",
        files={"file": ("duplicate-upload.gcode", content, "text/x.gcode")},
    )

    assert first_import.status_code == 201
    assert second_import.status_code == 201
    assert (
        second_import.json()["artifact"]["id"] == first_import.json()["artifact"]["id"]
    )


def test_importing_gcode_stores_bytes_by_their_sha256_content_identity(
    tmp_path: Path,
) -> None:
    content = b"; generated by test slicer\nG28\nG1 X10 Y10\n"
    storage = jobs.FileSystemStorage(tmp_path)
    service = jobs.ImportService(storage=storage)

    imported = cast(
        dict[str, Any],
        service.import_gcode(
            filename="calibration-cube.gcode",
            media_type="text/x.gcode",
            content=content,
        ),
    )

    artifact_id = imported["artifact"]["id"]
    assert artifact_id == f"sha256:{hashlib.sha256(content).hexdigest()}"
    assert storage.retrieve(artifact_id) == content


def test_retrieving_a_tampered_filesystem_artifact_detects_the_sha256_mismatch(
    tmp_path: Path,
) -> None:
    storage = jobs.FileSystemStorage(tmp_path)
    artifact_id = storage.store(
        filename="calibration-cube.gcode",
        media_type="text/x.gcode",
        content=b"G28\n",
    )
    (tmp_path / artifact_id.removeprefix("sha256:")).write_bytes(b"tampered bytes\n")

    with pytest.raises(ValueError, match="sha256"):
        storage.retrieve(artifact_id)


def test_active_queue_projection_survives_an_application_restart(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("calibration-cube.gcode", b"G28\n", "text/x.gcode")},
    )
    create_response = client.post(
        f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
        json={"material": "PLA"},
    )

    assert create_response.status_code == 201

    # Replacing the application service models a fresh process serving the same API.
    jobs.import_service = jobs.ImportService()

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": [create_response.json()]}


def test_created_job_persists_through_a_fresh_backend_application_for_the_active_queue(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("calibration-cube.gcode", b"G28\n", "text/x.gcode")},
    )
    create_response = client.post(
        f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
        json={"material": "PLA"},
    )

    assert create_response.status_code == 201

    # A fresh application must load the authoritative PostgreSQL job record.
    importlib.reload(jobs)
    importlib.reload(v1)
    restarted_main = importlib.reload(main)

    with TestClient(restarted_main.app) as restarted_client:
        queue_response = restarted_client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": [create_response.json()]}


def test_created_job_can_be_loaded_through_its_detail_projection_after_backend_restart(
    repo_root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    database_url = os.environ.get("PRINT_JOB_MANAGER_TEST_DATABASE_URL")
    if database_url is None:
        pytest.skip(
            "PRINT_JOB_MANAGER_TEST_DATABASE_URL must name a disposable PostgreSQL database"
        )

    schema = f"test_job_detail_{uuid4().hex}"
    admin_engine = sa.create_engine(database_url)
    with admin_engine.begin() as connection:
        connection.execute(sa.text(f'CREATE SCHEMA "{schema}"'))
    scoped_database_url = f"{database_url}?options=-csearch_path={schema}"
    monkeypatch.setenv("PRINT_JOB_MANAGER_DATABASE_URL", scoped_database_url)

    from backend.app import config as app_config
    from backend.app.persistence import database, job_repository, models

    app_config.get_settings.cache_clear()
    importlib.reload(database)
    importlib.reload(models)
    importlib.reload(job_repository)
    importlib.reload(jobs)
    importlib.reload(v1)
    reloaded_main = importlib.reload(main)

    alembic_config = Config(str(repo_root / "backend" / "alembic.ini"))
    alembic_config.set_main_option(
        "script_location", str(repo_root / "backend" / "alembic")
    )
    alembic_config.set_main_option("sqlalchemy.url", scoped_database_url)
    command.upgrade(alembic_config, "head")
    try:
        with TestClient(
            reloaded_main.app, raise_server_exceptions=False
        ) as test_client:
            import_response = test_client.post(
                "/api/v1/import",
                files={"file": ("calibration-cube.gcode", b"G28\n", "text/x.gcode")},
            )
            create_response = test_client.post(
                f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
                json={"material": "PLA"},
            )

        assert create_response.status_code == 201

        importlib.reload(jobs)
        importlib.reload(v1)
        restarted_main = importlib.reload(main)
        with TestClient(
            restarted_main.app, raise_server_exceptions=False
        ) as restarted_client:
            detail_response = restarted_client.get(
                f"/api/v1/jobs/{create_response.json()['id']}"
            )

        assert detail_response.status_code == 200
        assert detail_response.json() == create_response.json()
    finally:
        with admin_engine.begin() as connection:
            connection.execute(sa.text(f'DROP SCHEMA "{schema}" CASCADE'))
        admin_engine.dispose()


def test_in_memory_storage_retains_upload_bytes_by_its_canonical_artifact_reference() -> (
    None
):
    storage = jobs.InMemoryStorage()
    content = b"; generated by test slicer\nG28\n"

    artifact_ref = storage.store(
        filename="calibration-cube.gcode", media_type="text/x.gcode", content=content
    )

    assert storage.retrieve(artifact_ref) == content


def test_creating_a_job_from_an_import_without_required_material_is_rejected_and_leaves_queue_empty(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    create_response = client.post(
        f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
        json={},
    )

    assert create_response.status_code == 422
    assert create_response.json() == {
        "detail": {
            "missingPlanningValues": ["material"],
        }
    }

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": []}


def test_creating_a_job_with_a_json_array_body_returns_fastapi_validation_error(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    with TestClient(client.app, raise_server_exceptions=False) as error_client:
        response = error_client.post(
            f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
            json=[],
        )

    assert response.status_code == 422


def test_creating_a_job_with_blank_material_is_rejected_and_leaves_queue_empty(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    create_response = client.post(
        f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
        json={"material": " \t "},
    )

    assert create_response.status_code == 422
    assert create_response.json() == {
        "detail": {
            "missingPlanningValues": ["material"],
        }
    }

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": []}


def test_creating_a_job_from_an_unimported_artifact_is_rejected_and_does_not_queue_a_ready_job(
    client: TestClient,
) -> None:
    create_response = client.post(
        "/api/v1/import/artifact-unimported/jobs",
        json={"material": "PLA"},
    )

    assert create_response.status_code == 404

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": []}


def test_creating_a_job_with_all_missing_material_planning_values_returns_one_ready_job(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    assert import_response.status_code == 201
    artifact_id = import_response.json()["artifact"]["id"]

    create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs",
        json={"material": "PLA"},
    )

    assert create_response.status_code == 201
    job = create_response.json()
    assert job["state"] == "ready"
    assert job["executionData"] == {
        "artifactRef": artifact_id,
        "material": "PLA",
    }
    assert job["schedulingData"] == {"priority": 0}


def test_creating_a_complete_job_exposes_the_ready_job_in_the_active_queue_projection(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    create_response = client.post(
        f"/api/v1/import/{import_response.json()['artifact']['id']}/jobs",
        json={"material": "PLA"},
    )

    assert create_response.status_code == 201

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": [create_response.json()]}


def test_repeating_job_creation_for_one_import_returns_the_existing_ready_job_without_duplicating_the_queue(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("calibration-cube.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    first_create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"material": "PLA"}
    )
    repeated_create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"material": "PLA"}
    )

    assert first_create_response.status_code == 201
    assert repeated_create_response.status_code == 200
    assert repeated_create_response.json() == first_create_response.json()
    assert client.get("/api/v1/queue").json() == {
        "jobs": [first_create_response.json()]
    }


def test_two_create_requests_for_one_import_create_only_one_ready_queue_record(
    client: TestClient,
) -> None:
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("calibration-cube.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    with ThreadPoolExecutor(max_workers=2) as executor:
        responses = list(
            executor.map(
                lambda _: client.post(
                    f"/api/v1/import/{artifact_id}/jobs", json={"material": "PLA"}
                ),
                range(2),
            )
        )

    assert sorted(response.status_code for response in responses) == [200, 201]
    assert client.get("/api/v1/queue").json() == {"jobs": [responses[0].json()]}


def test_active_queue_retains_two_ready_jobs_in_creation_order(
    client: TestClient,
) -> None:
    first_import = client.post(
        "/api/v1/import",
        files={
            "file": (
                "first-part.gcode",
                b"; first artifact\nG28\n",
                "text/x.gcode",
            )
        },
    )
    second_import = client.post(
        "/api/v1/import",
        files={
            "file": (
                "second-part.gcode",
                b"; second artifact\nG1 X10 Y10\n",
                "text/x.gcode",
            )
        },
    )

    assert first_import.status_code == 201
    assert second_import.status_code == 201
    first_artifact_id = first_import.json()["artifact"]["id"]
    second_artifact_id = second_import.json()["artifact"]["id"]
    assert first_artifact_id != second_artifact_id

    first_job = client.post(
        f"/api/v1/import/{first_artifact_id}/jobs",
        json={"material": "PLA"},
    )
    second_job = client.post(
        f"/api/v1/import/{second_artifact_id}/jobs",
        json={"material": "PETG"},
    )

    assert first_job.status_code == 201
    assert second_job.status_code == 201

    queue_response = client.get("/api/v1/queue")

    assert queue_response.status_code == 200
    assert queue_response.json() == {"jobs": [first_job.json(), second_job.json()]}


def test_import_gcode_orchestrates_injected_storage_parser_and_repository_boundaries() -> (
    None
):
    calls: list[tuple[str, object]] = []

    class FakeStorage:
        def store(self, *, filename: str, media_type: str, content: bytes) -> str:
            calls.append(("storage", (filename, media_type, content)))
            return "artifact-from-storage"

    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            calls.append(("parser", (artifact_id, content)))
            return {"missingPlanningValues": ["material"], "diagnostics": []}

    class FakeRepository:
        @property
        def imported_artifact_ids(self) -> set[str]:
            return set()

        def save_import(
            self,
            *,
            artifact_id: str,
            filename: str,
            media_type: str,
            parsed: dict[str, object],
        ) -> None:
            calls.append(("repository", (artifact_id, filename, media_type, parsed)))

        def load_import(self, artifact_id: str) -> dict[str, object] | None:
            return None

    service = jobs.ImportService(
        storage=FakeStorage(), parser=FakeParser(), repository=FakeRepository()
    )

    imported = service.import_gcode(
        filename="part.gcode", media_type="text/x.gcode", content=b"G28\n"
    )

    assert imported == {
        "artifact": {
            "id": "artifact-from-storage",
            "filename": "part.gcode",
            "mediaType": "text/x.gcode",
        },
        "missingPlanningValues": ["material"],
        "diagnostics": [],
    }
    assert calls == [
        ("storage", ("part.gcode", "text/x.gcode", b"G28\n")),
        ("parser", ("artifact-from-storage", b"G28\n")),
        (
            "repository",
            (
                "artifact-from-storage",
                "part.gcode",
                "text/x.gcode",
                {"missingPlanningValues": ["material"], "diagnostics": []},
            ),
        ),
    ]


def test_creating_a_job_without_material_is_ready_when_the_import_parser_reports_no_missing_values() -> (
    None
):
    class FakeStorage:
        def store(self, *, filename: str, media_type: str, content: bytes) -> str:
            return "artifact-with-parsed-planning-data"

    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {"missingPlanningValues": [], "diagnostics": []}

    class FakeRepository:
        def __init__(self) -> None:
            self.imported_artifact_ids: set[str] = set()

        def save_import(
            self,
            *,
            artifact_id: str,
            filename: str,
            media_type: str,
            parsed: dict[str, object],
        ) -> None:
            self.imported_artifact_ids.add(artifact_id)

        def load_import(self, artifact_id: str) -> dict[str, object] | None:
            return None

    service = jobs.ImportService(
        storage=FakeStorage(), parser=FakeParser(), repository=FakeRepository()
    )
    imported = cast(
        dict[str, Any],
        service.import_gcode(
            filename="part-with-material.gcode",
            media_type="text/x.gcode",
            content=b"G28\n",
        ),
    )

    job = service.create_job(artifact_id=imported["artifact"]["id"], material=None)

    assert job["state"] == "ready"
    assert service.active_queue() == {"jobs": [job]}


def test_creating_a_job_requires_every_parser_reported_planning_value_before_queuing(
    client: TestClient, monkeypatch
) -> None:
    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {"missingPlanningValues": ["estimatedDuration"], "diagnostics": []}

    monkeypatch.setattr(jobs, "import_service", jobs.ImportService(parser=FakeParser()))
    import_response = client.post(
        "/api/v1/import",
        files={
            "file": (
                "calibration-cube.gcode",
                b"; generated by test slicer\nG28\n",
                "text/x.gcode",
            )
        },
    )
    artifact_id = import_response.json()["artifact"]["id"]

    missing_value_response = client.post(f"/api/v1/import/{artifact_id}/jobs", json={})

    assert missing_value_response.status_code == 422
    assert missing_value_response.json() == {
        "detail": {"missingPlanningValues": ["estimatedDuration"]}
    }
    assert client.get("/api/v1/queue").json() == {"jobs": []}

    supplied_value_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"estimatedDuration": 60}
    )

    assert supplied_value_response.status_code == 201
    assert supplied_value_response.json()["state"] == "ready"
    assert client.get("/api/v1/queue").json() == {
        "jobs": [supplied_value_response.json()]
    }


def test_creating_a_job_persists_a_parser_required_non_material_planning_value_in_execution_data(
    client: TestClient, monkeypatch
) -> None:
    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {"missingPlanningValues": ["estimatedDuration"], "diagnostics": []}

    monkeypatch.setattr(jobs, "import_service", jobs.ImportService(parser=FakeParser()))
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("part.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"estimatedDuration": 60}
    )

    assert create_response.status_code == 201
    assert create_response.json()["executionData"] == {
        "artifactRef": artifact_id,
        "material": None,
        "estimatedDuration": 60,
    }


def test_creating_a_ready_job_retains_parser_extracted_metadata_in_immutable_execution_data(
    client: TestClient, monkeypatch
) -> None:
    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {
                "extractedMetadata": {"estimatedDuration": 3600},
                "missingPlanningValues": [],
                "diagnostics": [],
            }

    monkeypatch.setattr(jobs, "import_service", jobs.ImportService(parser=FakeParser()))
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("part.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"material": "PLA"}
    )

    assert create_response.status_code == 201
    assert create_response.json()["state"] == "ready"
    assert create_response.json()["executionData"] == {
        "artifactRef": artifact_id,
        "material": "PLA",
        "extractedMetadata": {"estimatedDuration": 3600},
    }


def test_creating_a_ready_job_uses_material_extracted_by_the_parser(
    client: TestClient, monkeypatch
) -> None:
    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {
                "extractedMetadata": {"material": "PLA"},
                "missingPlanningValues": [],
                "diagnostics": [],
            }

    monkeypatch.setattr(jobs, "import_service", jobs.ImportService(parser=FakeParser()))
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("part.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    create_response = client.post(f"/api/v1/import/{artifact_id}/jobs", json={})

    assert create_response.status_code == 201
    assert create_response.json()["state"] == "ready"
    assert create_response.json()["executionData"]["material"] == "PLA"


def test_creating_a_job_does_not_allow_supplied_material_to_override_parser_material(
    client: TestClient, monkeypatch
) -> None:
    class FakeParser:
        def parse(self, *, artifact_id: str, content: bytes) -> dict[str, object]:
            return {
                "extractedMetadata": {"material": "PLA"},
                "missingPlanningValues": [],
                "diagnostics": [],
            }

    monkeypatch.setattr(jobs, "import_service", jobs.ImportService(parser=FakeParser()))
    import_response = client.post(
        "/api/v1/import",
        files={"file": ("part.gcode", b"G28\n", "text/x.gcode")},
    )
    artifact_id = import_response.json()["artifact"]["id"]

    create_response = client.post(
        f"/api/v1/import/{artifact_id}/jobs", json={"material": "PETG"}
    )

    assert create_response.status_code == 201
    assert create_response.json()["executionData"]["material"] == "PLA"
